# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_selfing_multi_rcpp <- function(n_mrk = 20L, map_len = 100.0, n_ind = 2000L, F_generations = 2L) {
    .Call(`_SIMpoly_simulate_selfing_multi_rcpp`, n_mrk, map_len, n_ind, F_generations)
}

